import React from 'react';
import Layout from "../components/Layout";
import Head from "next/head";

function Contact(props) {
    return (
        <Layout>
            <Head>
                <title>Andrew J. McCauley</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={"mt-10 text-center text-xl w-1/2 mx-auto"}>
                <div className={"text-sm p-20"}>Thank you for taking a few moments to look at my work and abilities. Please contact me via the details below! I look forward to hearing from you.</div>
                <div>Email: uxmccauley@gmail.com</div>
                <div>Phone: (608) 399-8607</div>
            </div>
        </Layout>
    );
}

export default Contact;
